# Generated by Django 3.2.3 on 2021-07-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='display',
            new_name='Transaction',
        ),
    ]
