# Generated by Django 3.2.3 on 2021-07-26 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_display_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
