# Generated by Django 3.2.3 on 2021-07-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_users_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_pub',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
