# Generated by Django 3.2.3 on 2021-08-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_information_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='balance',
        ),
        migrations.CreateModel(
            name='Moneytrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.users')),
            ],
        ),
    ]
