# Generated by Django 3.2.3 on 2021-08-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210830_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moneytrack',
        ),
    ]
