# Generated by Django 3.2.3 on 2021-08-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_users_balanace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='balanace',
            new_name='balance',
        ),
    ]
